imports:
    - { resource: local.yml }
    
parameters:        
        
services:
    doctrine:
        class: Doctrine\ORM\EntityManager
        factory_class:  ConsoleApplication
        factory_method: setupDoctrine
        arguments: [%dbal%]
        
    http-client:
        class: GuzzleHttp\Client
                    
    name-service:
        class: Service\NameService
        arguments: [ @gender-provider ]
