imports:
    - { resource: local.yml }
    
parameters:        
        
services:
    doctrine:
        class: Doctrine\ORM\EntityManager
        factory_class:  ConsoleApplication
        factory_method: setupDoctrine
        arguments: [ %dbal% ]
        
    http-client:
        # class: GuzzleHttp\Client # 4.*
        class: Guzzle\Http\Client
        
    name-service:
        class: Service\NameService
        arguments: [ @gender-provider ]

    gnd-service:
        class: Service\GndService
        arguments: [ @gnd-provider ]
